<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "faqjsonfiles"
 *
 * Auto generated by Extension Builder 2021-05-06
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'FAQ from json Files',
    'description' => 'Faq from json files',
    'category' => 'plugin',
    'author' => 'Stefan Wolfrath',
    'author_email' => 'stefan.wolfrath@bitsfabrik.com',
    'state' => 'alpha',
    'uploadfolder' => '',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
